#!/bin/sh
APPDIR=$(dirname "$0")
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    exec "$APPDIR/usr/bin/printer-installer-x86" "$@"
elif [ "$ARCH" = "aarch64" ]; then
    exec "$APPDIR/usr/bin/printer-installer-arm64" "$@"
else
    echo "Unsupported architecture: $ARCH" 1>&2
    exit 1
fi
